### PR TITLE
Using ES6 classes

### PR DESCRIPTION
**Pull request by samuelsimoes**
Plain objects are great, but sometime you gonna need "blueprints" (or mixins) to your stores instances and between a fluxo pumped object and a mixin object the only identifier may be the name and it causes confusion to newcomers, we introduce new concepts and it discourages patterns.

On other hand, the `class` and instance bring the solid and known concepts to most developers about the difference between "blueprint" and instance.

Since we already have babel in the project this PR convert Fluxo to ES6 class through babel.

TODO: update the docs (I'll utilize the branch `samuel/new-readme` to this).

Obs.: maybe develop some way to use (extend) this on non ES6 envs.

### CODE REVIEW

**Comment by samuelsimoes** [comment]
@sobrinho :point_up:

**Comment by sobrinho** [comment]
:shipit:

**Comment by sobrinho** [comment]
Needs rebase since #11 got merged.

**Comment by samuelsimoes** [comment]
Yes, I'll do :)

**Pull request merged**
