### PR TITLE
Removing subsets

### PR DESCRIPTION
**Pull request by samuelsimoes**
#42

### CODE REVIEW

**Comment by sobrinho** [comment]
Seems great although I think we need a CHANGELOG to start warning user about these kind of breaking changes 👍

**Comment by fnmunhoz** [comment]
@samuelsimoes @sobrinho computed properties already do the same thing computed properties do?

The diff shows only code being removed, so I suppose that I can use computed properties in my current Fluxo version (v0.0.23)?

Am I missing something?

**Comment by sobrinho** [comment]
@fnmunhoz exactly, you can just use computed instead of subset and everything will work as before :)

There is some internal differences on Fluxo but from the outside, nothing changes.

**Comment by fnmunhoz** [comment]
@sobrinho perfect, thanks!

**Comment by sobrinho** [comment]
@samuelsimoes :shipit:

**Pull request merged**
